<?xml version="1.0" encoding="utf-8"?><Database Name="platformathletics" Class="platformAthleticDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SATURN\MSSQL;Initial Catalog=platformathletics;Integrated Security=True" SettingsObjectName="platformAthletic.Model.Properties.Settings" SettingsPropertyName="platformathleticsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserSeason" Member="UserSeasons">
    <Type Name="UserSeason">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SeasonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDay" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserSeason_UserAttendance" Member="UserAttendances" ThisKey="ID" OtherKey="UserSeasonID" Type="UserAttendance" />
      <Association Name="UserSeason_PersonalSchedule" Member="PersonalSchedules" ThisKey="ID" OtherKey="UserSeasonID" Type="PersonalSchedule" />
      <Association Name="UserSeason_Schedule" Member="Schedules" ThisKey="ID" OtherKey="UserSeasonID" Type="Schedule" />
      <Association Name="Season_UserSeason" Member="Season" ThisKey="SeasonID" OtherKey="ID" Type="Season" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_UserSeason" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Equipment" Member="Equipments">
    <Type Name="Equipment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="Equipment_UserEquipment" Member="UserEquipments" ThisKey="ID" OtherKey="EquipmentID" Type="UserEquipment" />
      <Association Name="Equipment_TrainingEquipment" Member="TrainingEquipments" ThisKey="ID" OtherKey="EquipmentID" Type="TrainingEquipment" />
      <Association Name="Equipment_TrainingEquipment1" Member="TrainingEquipments1" ThisKey="ID" OtherKey="Equipment2ID" Type="TrainingEquipment" />
    </Type>
  </Table>
  <Table Name="dbo.FeatureText" Member="FeatureTexts">
    <Type Name="FeatureText">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FeatureCatalogID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Header" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="FeatureCatalog_FeatureText" Member="FeatureCatalog" ThisKey="FeatureCatalogID" OtherKey="ID" Type="FeatureCatalog" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Page" Member="Pages">
    <Type Name="Page">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="ID" OtherKey="RoleID" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.Season" Member="Seasons">
    <Type Name="Season">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Season_UserSeason" Member="UserSeasons" ThisKey="ID" OtherKey="SeasonID" Type="UserSeason" />
      <Association Name="Season_Cycle" Member="Cycles" ThisKey="ID" OtherKey="SeasonID" Type="Cycle" />
    </Type>
  </Table>
  <Table Name="dbo.State" Member="States">
    <Type Name="State">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="State_BillingInfo" Member="BillingInfos" ThisKey="ID" OtherKey="StateID" Type="BillingInfo" />
      <Association Name="State_Feedback" Member="Feedbacks" ThisKey="ID" OtherKey="StateID" Type="Feedback" />
      <Association Name="State_Invoice" Member="Invoices" ThisKey="ID" OtherKey="StateID" Type="Invoice" />
      <Association Name="State_Team" Member="Teams" ThisKey="ID" OtherKey="StateID" Type="Team" />
    </Type>
  </Table>
  <Table Name="dbo.Training" Member="Trainings">
    <Type Name="Training">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Training_TrainingEquipment" Member="TrainingEquipments" ThisKey="ID" OtherKey="TrainingID" Type="TrainingEquipment" />
      <Association Name="Training_Video" Member="Videos" ThisKey="ID" OtherKey="TrainingID" Type="Video" />
    </Type>
  </Table>
  <Table Name="dbo.UserEquipment" Member="UserEquipments">
    <Type Name="UserEquipment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Equipment_UserEquipment" Member="Equipment" ThisKey="EquipmentID" OtherKey="ID" Type="Equipment" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_UserEquipment" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleID" OtherKey="ID" Type="Role" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phase" Member="Phases">
    <Type Name="Phase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CycleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Phase_TrainingSet" Member="TrainingSets" ThisKey="ID" OtherKey="PhaseID" Type="TrainingSet" />
      <Association Name="Phase_Week" Member="Weeks" ThisKey="ID" OtherKey="PhaseID" Type="Week" />
      <Association Name="Cycle_Phase" Member="Cycle" ThisKey="CycleID" OtherKey="ID" Type="Cycle" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cycle" Member="Cycles">
    <Type Name="Cycle">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SeasonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Cycle_Phase" Member="Phases" ThisKey="ID" OtherKey="CycleID" Type="Phase" />
      <Association Name="Season_Cycle" Member="Season" ThisKey="SeasonID" OtherKey="ID" Type="Season" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrainingEquipment" Member="TrainingEquipments">
    <Type Name="TrainingEquipment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrainingSetID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrainingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Equipment2ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Equipment_TrainingEquipment" Member="Equipment" ThisKey="EquipmentID" OtherKey="ID" Type="Equipment" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Equipment_TrainingEquipment1" Member="Equipment1" ThisKey="Equipment2ID" OtherKey="ID" Type="Equipment" IsForeignKey="true" />
      <Association Name="Training_TrainingEquipment" Member="Training" ThisKey="TrainingID" OtherKey="ID" Type="Training" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TrainingSet_TrainingEquipment" Member="TrainingSet" ThisKey="TrainingSetID" OtherKey="ID" Type="TrainingSet" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Day" Member="Days">
    <Type Name="Day">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Day_TrainingSet" Member="TrainingSets" ThisKey="ID" OtherKey="DayID" Type="TrainingSet" />
      <Association Name="Day_TrainingDay" Member="TrainingDays" ThisKey="ID" OtherKey="DayID" Type="TrainingDay" />
    </Type>
  </Table>
  <Table Name="dbo.TrainingSet" Member="TrainingSets">
    <Type Name="TrainingSet">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DayID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TrainingSet_TrainingEquipment" Member="TrainingEquipments" ThisKey="ID" OtherKey="TrainingSetID" Type="TrainingEquipment" />
      <Association Name="TrainingSet_TrainingDayCell" Member="TrainingDayCells" ThisKey="ID" OtherKey="TrainingSetID" Type="TrainingDayCell" />
      <Association Name="Day_TrainingSet" Member="Day" ThisKey="DayID" OtherKey="ID" Type="Day" IsForeignKey="true" />
      <Association Name="Phase_TrainingSet" Member="Phase" ThisKey="PhaseID" OtherKey="ID" Type="Phase" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cell" Member="Cells">
    <Type Name="Cell">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Cell_TrainingDayCell" Member="TrainingDayCells" ThisKey="ID" OtherKey="CellID" Type="TrainingDayCell" />
    </Type>
  </Table>
  <Table Name="dbo.TrainingDayCell" Member="TrainingDayCells">
    <Type Name="TrainingDayCell">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CellID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrainingDayID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryText" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrainingSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SBCType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Coefficient" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Cell_TrainingDayCell" Member="Cell" ThisKey="CellID" OtherKey="ID" Type="Cell" IsForeignKey="true" />
      <Association Name="TrainingSet_TrainingDayCell" Member="TrainingSet" ThisKey="TrainingSetID" OtherKey="ID" Type="TrainingSet" IsForeignKey="true" />
      <Association Name="TrainingDay_TrainingDayCell" Member="TrainingDay" ThisKey="TrainingDayID" OtherKey="ID" Type="TrainingDay" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Setting" Member="Settings">
    <Type Name="Setting">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PromoAction" Member="PromoActions">
    <Type Name="PromoAction">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Target" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ValidDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Closed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Reusable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="PromoAction_PromoCode" Member="PromoCodes" ThisKey="ID" OtherKey="PromoActionID" Type="PromoCode" />
    </Type>
  </Table>
  <Table Name="dbo.PromoCode" Member="PromoCodes">
    <Type Name="PromoCode">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PromoActionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReferralCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UsedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PromoAction_PromoCode" Member="PromoAction" ThisKey="PromoActionID" OtherKey="ID" Type="PromoAction" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserAttendance" Member="UserAttendances">
    <Type Name="UserAttendance">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserSeasonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserSeason_UserAttendance" Member="UserSeason" ThisKey="UserSeasonID" OtherKey="ID" Type="UserSeason" IsForeignKey="true" />
      <Association Name="User_UserAttendance" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Video" Member="Videos">
    <Type Name="Video">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrainingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Header" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VideoUrl" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="VideoCode" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Training_Video" Member="Training" ThisKey="TrainingID" OtherKey="ID" Type="Training" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FeatureCatalog" Member="FeatureCatalogs">
    <Type Name="FeatureCatalog">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Header" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="OrderBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FeatureCatalog_FeatureText" Member="FeatureTexts" ThisKey="ID" OtherKey="FeatureCatalogID" Type="FeatureText" />
    </Type>
  </Table>
  <Table Name="dbo.[File]" Member="Files">
    <Type Name="File">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Preview" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Faq" Member="Faqs">
    <Type Name="Faq">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Header" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="OrderBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BannerPlace" Member="BannerPlaces">
    <Type Name="BannerPlace">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BannerPlace_Banner" Member="Banners" ThisKey="ID" OtherKey="BannerPlaceID" Type="Banner" />
    </Type>
  </Table>
  <Table Name="dbo.BillingInfo" Member="BillingInfos">
    <Type Name="BillingInfo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AutoDebit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NameOnCard" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="BillingAddress" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CardType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreditCardNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ExparationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CVC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="State_BillingInfo" Member="State" ThisKey="StateID" OtherKey="ID" Type="State" IsForeignKey="true" />
      <Association Name="User_BillingInfo" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.About" Member="Abouts">
    <Type Name="About">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Feedback" Member="Feedbacks">
    <Type Name="Feedback">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="School" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsReaded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="State_Feedback" Member="State" ThisKey="StateID" OtherKey="ID" Type="State" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FieldPosition" Member="FieldPositions">
    <Type Name="FieldPosition">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="FieldPosition_SBCValue" Member="SBCValues" ThisKey="ID" OtherKey="FieldPositionID" Type="SBCValue" />
      <Association Name="FieldPosition_User" Member="Users" ThisKey="ID" OtherKey="FieldPositionID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Gallery" Member="Galleries">
    <Type Name="Gallery">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Post" Member="Posts">
    <Type Name="Post">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Header" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Post" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Banner" Member="Banners">
    <Type Name="Banner">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BannerPlaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SourcePath" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="InRotation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="BannerPlace_Banner" Member="BannerPlace" ThisKey="BannerPlaceID" OtherKey="ID" Type="BannerPlace" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCValue" Member="SBCValues">
    <Type Name="SBCValue">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FieldPositionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Squat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Bench" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Clean" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="FieldPosition_SBCValue" Member="FieldPosition" ThisKey="FieldPositionID" OtherKey="ID" Type="FieldPosition" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="User_SBCValue" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Team_SBCValue" Member="Team" ThisKey="TeamID" OtherKey="ID" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PillarType" Member="PillarTypes">
    <Type Name="PillarType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Placeholder" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Measure" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TextAbove" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="VideoUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="VideoCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="PillarType_UserPillar" Member="UserPillars" ThisKey="ID" OtherKey="PillarTypeID" Type="UserPillar" />
    </Type>
  </Table>
  <Table Name="dbo.UserPillar" Member="UserPillars">
    <Type Name="UserPillar">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PillarTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TextValue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PillarType_UserPillar" Member="PillarType" ThisKey="PillarTypeID" OtherKey="ID" Type="PillarType" IsForeignKey="true" />
      <Association Name="User_UserPillar" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentDetail" Member="PaymentDetails">
    <Type Name="PaymentDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReferralCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProcessedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="User_PaymentDetail" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FailedMail" Member="FailedMails">
    <Type Name="FailedMail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsProcessed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FailEmail" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Macrocycle" Member="Macrocycles">
    <Type Name="Macrocycle">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WeekID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Macrocycle_TrainingDay" Member="TrainingDays" ThisKey="ID" OtherKey="MacrocycleID" Type="TrainingDay" />
      <Association Name="Macrocycle_PersonalSchedule" Member="PersonalSchedules" ThisKey="ID" OtherKey="MacrocycleID" Type="PersonalSchedule" />
      <Association Name="Macrocycle_Schedule" Member="Schedules" ThisKey="ID" OtherKey="MacrocycleID" Type="Schedule" />
      <Association Name="Week_Macrocycle" Member="Week" ThisKey="WeekID" OtherKey="ID" Type="Week" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrainingDay" Member="TrainingDays">
    <Type Name="TrainingDay">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WeekID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MacrocycleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DayID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TrainingDay_TrainingDayCell" Member="TrainingDayCells" ThisKey="ID" OtherKey="TrainingDayID" Type="TrainingDayCell" />
      <Association Name="Day_TrainingDay" Member="Day" ThisKey="DayID" OtherKey="ID" Type="Day" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Macrocycle_TrainingDay" Member="Macrocycle" ThisKey="MacrocycleID" OtherKey="ID" Type="Macrocycle" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Week_TrainingDay" Member="Week" ThisKey="WeekID" OtherKey="ID" Type="Week" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Week" Member="Weeks">
    <Type Name="Week">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Week_Macrocycle" Member="Macrocycles" ThisKey="ID" OtherKey="WeekID" Type="Macrocycle" />
      <Association Name="Week_TrainingDay" Member="TrainingDays" ThisKey="ID" OtherKey="WeekID" Type="TrainingDay" />
      <Association Name="Phase_Week" Member="Phase" ThisKey="PhaseID" OtherKey="ID" Type="Phase" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ActivatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActivatedLink" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastVisitDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AvatarPath" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PaidTill" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PlayerOfTeamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FieldPositionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VisitGettingStartedPage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Squat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Bench" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Clean" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Weight" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BodyFat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[_40YardDash]" Member="_40YardDash" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Vertical" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[_3Cone]" Member="_3Cone" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TDrill" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PrimaryColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SecondaryColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoginInfoSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AttendanceStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProgressStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_UserSeason" Member="UserSeasons" ThisKey="ID" OtherKey="UserID" Type="UserSeason" />
      <Association Name="User_UserEquipment" Member="UserEquipments" ThisKey="ID" OtherKey="UserID" Type="UserEquipment" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="ID" OtherKey="UserID" Type="UserRole" />
      <Association Name="User_UserAttendance" Member="UserAttendances" ThisKey="ID" OtherKey="UserID" Type="UserAttendance" />
      <Association Name="User_BillingInfo" Member="BillingInfos" ThisKey="ID" OtherKey="UserID" Type="BillingInfo" />
      <Association Name="User_Post" Member="Posts" ThisKey="ID" OtherKey="UserID" Type="Post" />
      <Association Name="User_SBCValue" Member="SBCValues" ThisKey="ID" OtherKey="UserID" Type="SBCValue" />
      <Association Name="User_UserPillar" Member="UserPillars" ThisKey="ID" OtherKey="UserID" Type="UserPillar" />
      <Association Name="User_PaymentDetail" Member="PaymentDetails" ThisKey="ID" OtherKey="UserID" Type="PaymentDetail" />
      <Association Name="User_PersonalSchedule" Member="PersonalSchedules" ThisKey="ID" OtherKey="UserID" Type="PersonalSchedule" />
      <Association Name="User_Invoice" Member="Invoices" ThisKey="ID" OtherKey="UserID" Type="Invoice" />
      <Association Name="User_Team" Member="Teams" ThisKey="ID" OtherKey="UserID" Type="Team" />
      <Association Name="FieldPosition_User" Member="FieldPosition" ThisKey="FieldPositionID" OtherKey="ID" Type="FieldPosition" IsForeignKey="true" />
      <Association Name="Group_User" Member="Group" ThisKey="GroupID" OtherKey="ID" Type="Group" IsForeignKey="true" />
      <Association Name="Team_User" Member="Team" ThisKey="PlayerOfTeamID" OtherKey="ID" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalSchedule" Member="PersonalSchedules">
    <Type Name="PersonalSchedule">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserSeasonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MacrocycleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Macrocycle_PersonalSchedule" Member="Macrocycle" ThisKey="MacrocycleID" OtherKey="ID" Type="Macrocycle" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_PersonalSchedule" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="UserSeason_PersonalSchedule" Member="UserSeason" ThisKey="UserSeasonID" OtherKey="ID" Type="UserSeason" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedule" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserSeasonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MacrocycleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Macrocycle_Schedule" Member="Macrocycle" ThisKey="MacrocycleID" OtherKey="ID" Type="Macrocycle" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="UserSeason_Schedule" Member="UserSeason" ThisKey="UserSeasonID" OtherKey="ID" Type="UserSeason" IsForeignKey="true" />
      <Association Name="Group_Schedule" Member="Group" ThisKey="GroupID" OtherKey="ID" Type="Group" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Team_Schedule" Member="Team" ThisKey="TeamID" OtherKey="ID" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PagePart" Member="PageParts">
    <Type Name="PagePart">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Aphorism" Member="Aphorisms">
    <Type Name="Aphorism">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PeopleSaying" Member="PeopleSayings">
    <Type Name="PeopleSaying">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="NameOfOrganization" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateSent" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDue" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TotalSum" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="State_Invoice" Member="State" ThisKey="StateID" OtherKey="ID" Type="State" IsForeignKey="true" />
      <Association Name="User_Invoice" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Groups">
    <Type Name="Group">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeamID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Group_User" Member="Users" ThisKey="ID" OtherKey="GroupID" Type="User" />
      <Association Name="Group_Schedule" Member="Schedules" ThisKey="ID" OtherKey="GroupID" Type="Schedule" />
      <Association Name="Team_Group" Member="Team" ThisKey="TeamID" OtherKey="ID" Type="Team" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Team" Member="Teams">
    <Type Name="Team">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LogoPath" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryColor" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SecondaryColor" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SBCControl" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Team_SBCValue" Member="SBCValues" ThisKey="ID" OtherKey="TeamID" Type="SBCValue" />
      <Association Name="Team_User" Member="Users" ThisKey="ID" OtherKey="PlayerOfTeamID" Type="User" />
      <Association Name="Team_Schedule" Member="Schedules" ThisKey="ID" OtherKey="TeamID" Type="Schedule" />
      <Association Name="Team_Group" Member="Groups" ThisKey="ID" OtherKey="TeamID" Type="Group" />
      <Association Name="State_Team" Member="State" ThisKey="StateID" OtherKey="ID" Type="State" IsForeignKey="true" />
      <Association Name="User_Team" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>